# Generated by Django 2.2.1 on 2019-08-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_yosoku_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yosoku_date', models.DateField()),
                ('product_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toppage.Product_series')),
            ],
        ),
    ]
