# Generated by Django 2.2.1 on 2019-08-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product_series',
            name='hatubaibi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_series',
            name='product_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='toppage.Product_line'),
        ),
    ]
