# Generated by Django 2.2.1 on 2019-08-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0002_auto_20190814_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_series',
            name='yosoku_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_yosoku_date',
            name='product_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='toppage.Product_series'),
        ),
    ]
