# Generated by Django 2.2.1 on 2019-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0003_auto_20190815_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
            ],
        ),
    ]
