# Generated by Django 2.2.1 on 2019-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
